package com.lerchenflo.taximeter.datasource.database

import androidx.room.ConstructedBy
import androidx.room.Database
import androidx.room.RoomDatabase
import androidx.room.RoomDatabaseConstructor
import com.lerchenflo.taximeter.datasource.database.entities.MapEntry

@Database(
    entities = [MapEntry::class ],
    version = 1,
    exportSchema = true
)
@ConstructedBy(AppDatabaseConstructor::class)
abstract class AppDatabase : RoomDatabase() {

    abstract fun mapEntry(): MapEntryDao

    companion object {
        const val DB_NAME = "database.db"
    }
}

// Generated by Room/KSP (not checked in)
expect object AppDatabaseConstructor : RoomDatabaseConstructor<AppDatabase> {
    override fun initialize(): AppDatabase
}
